### ISSUE TITLE
Access Codes - Align with FCC

### ISSUE THREAD

**Issue by jlivingood** [jlivingood/Broadband-Labels#1]
From Jacob: 
One thing that came to mind as I was reading through is aligning the Access Network Technology Codes to what the FCC uses in the Broadband Map ([https://www.fcc.gov/general/technology-codes-used-fixed-broadband-deployment-data]). Even if it was not used 1:1, something like this could be used as a prefix to make parsing easier. For data analysis, this would limit any type of crosswalk file that would be needed and tends to plague any use of data from the Census and other agencies.

**Comment by mconlow** [comment]
The technology codes in the BDC data are actually documented here, and have lost the DOCSIS version: https://help.bdc.fcc.gov/hc/en-us/articles/5290793888795-Fixed-Technology-Codes.  That DOCSIS version was actually helpful and I think it'd be useful to think about how to include it here. 

But/and also it would be helpful to link to the FCC technology codes. Perhaps an adapted version of what they did with F477 codes? Where the 40s are the DOCSIS version but adding the 50s for FTTP architectures?

**Comment by jlivingood** [comment]
Ack! Addressing in 1st draft BITAG doc.
