### ISSUE TITLE
Why CSV? Alternative formats

### ISSUE THREAD

**Issue by jlivingood** [jlivingood/Broadband-Labels#3]
The FCC doc mentions CSV but in a way that means it is not limiting - other formats may be used. 

1. ISPs must take steps to ensure that
the information contained in the labels is publicly available via a dedicated URL in a machine-readable
format, and that the labels include a **unique identification code** to assist third parties and researchers in
compiling broadband data to help consumers compare service offerings amongst providers. 

2. Providers should make each label’s information available by
providing the information separately in a spreadsheet file format **such as .csv.** These files should be made
available on a provider’s website **via a dedicated URL** that contains all of a provider’s given labels. We
require providers to publicize the URL with the label data in the transparency disclosures required under
47 CFR § 8.1(a). These machine-readable files must provide the same categories of information as those
presented in each label, including the unique identifier described below. We direct CGB, in consultation
with other relevant bureaus, to make available on the Commission’s website resources that may help
providers satisfy the machine-readability requirement, such as sample machine-readable spreadsheet
files.144 Further, given the importance of this requirement, we will monitor providers’ implementation of
machine readability to ensure providers’ implementation of this requirement is useful to third parties and
the Commission in its data collection efforts.

_Footnote:_ 

144 AARP Reply at 9-11 (stating that machine-readable data requires a consistent structured data format, which could
be enabled by the Commission providing an API for inputting data, or by providing a template in Excel format, to
allow the creation of information in both .csv and .xml formats and the machine-readable format requirement should
impose no significant burden on the ISP).

**Comment by dorkmatt** [comment]
> unique identification code

Consider use of UUID

> dedicated URL

Consider the use of a `/.well-known/latest-broadband-label.extension` location. This could be encoded in a JPEG EXIF comment area, SVG <metadata>, etc. to advertise the URL.

> AARL's suggestion of Excel format

By definition, an Excel file is not an open format machine readable format. Suggest CSV _(low barrier - difficult to enumerate enhancements over time)_, YAML/JSON _(preferred)_, or XML _(fairly out of vogue these days)_.

**Comment by jlivingood** [comment]
Added to draft 1 of BITAG report: 
> By definition, an Excel file is not an open format machine readable format. Suggest CSV (low barrier - difficult to enumerate enhancements over time), YAML/JSON (preferred), or XML (fairly out of vogue these days).

**Comment by jlivingood** [comment]
@dorkmatt  Did you get added to the BITAG report we're working on yet? Ping me jason_livingood@comcast.com and Doug dsicker@bitag.org if you'd like to collaborate on this paper.

**Comment by jlivingood** [comment]
Adding to the BITAG draft
> Consider use of UUID

**Comment by jlivingood** [comment]
Added to BITAG draft issues to discuss

> Consider the use of a /.well-known/latest-broadband-label.extension location. This could be encoded in a JPEG EXIF comment area, SVG , etc. to advertise the URL.

**Comment by jlivingood** [comment]
add now ported to repo for BITAG WG on this

**Comment by dorkmatt** [comment]
Not added at this point

> @dorkmatt Did you get added to the BITAG report we're working on yet? Ping me [jason_livingood@comcast.com](mailto:jason_livingood@comcast.com) and Doug [dsicker@bitag.org](mailto:dsicker@bitag.org) if you'd like to collaborate on this paper.
