### ISSUE TITLE
FRN and provider_id

### ISSUE THREAD

**Issue by mconlow** [jlivingood/Broadband-Labels#4]
Do you think providers would be willing to add the FCC FRN and ProviderID? Those are FCC assigned (I believe) and would allow easier matching to the BDC data

**Comment by mconlow** [comment]
I now see this requirement which I think probably provides the necessary data: 

`We require ISPs to develop unique identifiers for each of their plans and attach them to the broadband label. The unique identifier should consist of a unique ID for fixed plan or mobile plan (“F” for fixed plans and “M” for mobile plans), followed by the broadband provider’s FCC Registration Number,178 and ending with a provider-chosen string of precisely 15 alphanumeric characters uniquely identifying the specific plan within the broadband provider’s offerings.`

**Comment by jlivingood** [comment]
Ack. Added to the 1st draft BITAG report.
